CREATE TABLE combined_data(
    ID INT PRIMARY KEY,
    Year INT,
    Geography VARCHAR(200),
    American_Indian/Alaska_Native INT,
    Asian INT,
    Black/African_American INT,
    Hispanic/Latino INT,
    Multiracial INT,
    Native_Hawaiian/Other_Pacific_Islander INT,
    Unknown INT,
    White INT,
    Female INT,
    Male INT,
    Non-U.S.–born INT,
    U.S.-born INT,
    0-4 INT,
    15-24 INT,
    25-34 INT,
    35-44 INT,
    45-54 INT,
    14-May INT,
    55-64 INT,
    65+ INT,
    Combined INT
);
